version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      FULL_DATABASE_URL: postgresql://postgres:postgres_password@db:5432/postgres
      DATABASE_URL: postgresql://db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres_password
    command: bash scripts/run_on_docker.sh


  db:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: 
    driver: local
